
pool:
  vmImage: ubuntu-latest

steps:
- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'Other'
    extraProperties: 'sonar.projectKey=sonar.projectKey'
- task: MavenAuthenticate@0
  inputs:
    mavenServiceConnections: 'nexus'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    sonarQubeRunAnalysis: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package deploy'
- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'

- task: Docker@2
  inputs:
    containerRegistry: 'ACR'
    repository: 'my-maven-webapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
